# POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/fleet
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# En prod mejor controlar migraciones
spring.jpa.hibernate.ddl-auto=validate

# Logging más limpio
logging.level.root=INFO
logging.level.com.acoes=INFO